---

- hosts: all
  become: true
  tasks:
 
  - name: Install apache package & add php support.
    package:
      name:
        - "{{ apache }}"
        - "{{ php }}"

      state: latest
      update_cache: yes



